"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Check,ChevronLeft,Grid3X3,Sparkles,Shuffle} from "lucide-react";
type Choice={title:string,mode:string,challenge:string,product:string};
const empty=()=>({title:"",mode:"",challenge:"",product:""});
export default function XOBuilder(){
 const [step,setStep]=useState(1),[subject,setSubject]=useState(""),[grade,setGrade]=useState(""),[lesson,setLesson]=useState(""),[goal,setGoal]=useState(""),[size,setSize]=useState(9),[rule,setRule]=useState("اختر 3 مهام تكوّن خطًا متصلًا"),[choices,setChoices]=useState<Choice[]>(Array.from({length:12},empty));
 const valid=useMemo(()=>subject.trim()&&lesson.trim()&&goal.trim(),[subject,lesson,goal]);
 function update(i:number,k:keyof Choice,v:string){setChoices(x=>x.map((c,n)=>n===i?{...c,[k]:v}:c))}
 const active=choices.slice(0,size);
 return <main className="xoBuilder">
  <header className="tierTop"><Link href="/teacher/lab">مختبر التمايز <ArrowLeft size={14}/></Link><div><Grid3X3/><b>إكس / أو</b></div><span>مصمم الاختيار المقصود</span></header>
  <section className="tierIntro"><span>أداة 04 • الاختيار المقصود</span><h1>امنح خيارات حقيقية.<br/>لكن لا تجعل الاختيار عشوائيًا.</h1><p>صمّم مجموعة مهام ومنتجات تحقق ناتج التعلم نفسه بطرق متنوعة، ثم ضع قاعدة اختيار واضحة تحفظ التحدي وتمنح المتعلم مساحة للقرار.</p></section>
  <nav className="builderSteps">{["الهدف","بنية اللوحة","تصميم الخيارات","المراجعة"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
  {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>ثبّت الهدف المشترك أولًا</h2><p>الطالب يختار طريق التعبير أو المهمة، لا أن يختار هل يتعلم الهدف أم لا.</p></div></div><div className="formGrid"><label>المادة<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="مثال: اللغة العربية"/></label><label>الصف<input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="مثال: أول ثانوي"/></label><label className="wide">عنوان الدرس<input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="عنوان الدرس"/></label><label className="wide">ناتج التعلم<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="ما الذي يجب أن تثبت جميع الخيارات تعلمه؟"/></label></div><button className="builderNext" disabled={!valid} onClick={()=>setStep(2)}>تصميم لوحة الاختيار <ChevronLeft/></button></section>}
  {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>اختر بنية الخيارات وقاعدة اللعب</h2><p>كلما زادت الخيارات، احرص على أن تبقى ذات غرض وأن تتوزع على طرق تعبير ومستويات تحدٍ مفيدة.</p></div></div><div className="xoSizes">{[6,9,12].map(n=><button key={n} onClick={()=>setSize(n)} className={size===n?"active":""}><Grid3X3/><b>{n} خيارات</b><span>{n===6?"لوحة مركزة":n===9?"شبكة 3 × 3":"لوحة موسعة"}</span></button>)}</div><label className="standalone xoRule">قاعدة الاختيار<input value={rule} onChange={e=>setRule(e.target.value)} placeholder="مثال: اختر 3 مهام تكوّن خطًا متصلًا"/></label><div className="choicePrinciples"><div><b>الاهتمام</b><span>هل يجد الطالب مدخلًا ذا معنى له؟</span></div><div><b>طريقة التعبير</b><span>هل تتنوع طرق إظهار التعلم؟</span></div><div><b>التحدي</b><span>هل تمنع اللوحة اختيار الطريق الأسهل دائمًا؟</span></div><div><b>الهدف</b><span>هل جميع الطرق تعود إلى ناتج التعلم؟</span></div></div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" onClick={()=>setStep(3)}>كتابة الخيارات <ChevronLeft/></button></div></section>}
  {step===3&&<section className="builderCard wideCard"><div className="builderHead"><span>03</span><div><h2>صمّم خيارات متوازنة</h2><p>لكل خيار: مهمة واضحة، طريقة تعبير، مستوى تحدٍ، ومنتج أو دليل تعلم.</p></div></div><div className={"xoEditor size"+size}>{active.map((c,i)=><article key={i}><span>{String(i+1).padStart(2,"0")}</span><input value={c.title} onChange={e=>update(i,"title",e.target.value)} placeholder="عنوان المهمة"/><select value={c.mode} onChange={e=>update(i,"mode",e.target.value)}><option value="">طريقة التعبير</option><option>كتابي</option><option>شفهي</option><option>بصري</option><option>تقني</option><option>عملي / أدائي</option></select><select value={c.challenge} onChange={e=>update(i,"challenge",e.target.value)}><option value="">مستوى التحدي</option><option>L1 • دعم موجّه</option><option>L2 • إتقان</option><option>L3 • تحدٍ ممتد</option></select><textarea value={c.product} onChange={e=>update(i,"product",e.target.value)} placeholder="المهمة / المنتج المطلوب"/></article>)}</div><div className="xoBalance"><Shuffle/><div><b>مؤشر التوازن</b><span>{new Set(active.map(c=>c.mode).filter(Boolean)).size} طرق تعبير • {new Set(active.map(c=>c.challenge).filter(Boolean)).size} مستويات تحدٍ • {active.filter(c=>c.title&&c.product).length}/{size} خيارات مكتملة</span></div></div><div className="builderActions"><button onClick={()=>setStep(2)}>السابق</button><button className="builderNext" onClick={()=>setStep(4)}>معاينة اللوحة <ChevronLeft/></button></div></section>}
  {step===4&&<section className="builderCard reviewCard"><div className="builderHead"><span>04</span><div><h2>لوحة إكس / أو</h2><p>{subject} • {grade} • {lesson}</p></div></div><div className="goalReview"><span>الهدف المشترك</span><b>{goal}</b><small>قاعدة الاختيار: {rule}</small></div><div className={"xoBoard board"+size}>{active.map((c,i)=><article key={i}><span>{c.mode||"اختيار"}</span><b>{c.title||("المهمة "+(i+1))}</b><p>{c.product||"لم تُكتب المهمة بعد."}</p><div><small>{c.challenge||"التحدي غير محدد"}</small></div></article>)}</div><div className="vennQuality"><Check/><span>جميع الخيارات تخدم الهدف.</span><Check/><span>اللوحة تقدم طرق تعبير متعددة.</span><Check/><span>قاعدة الاختيار تمنع الاختيار العشوائي أو الأسهل دائمًا.</span></div><div className="builderActions"><button onClick={()=>setStep(3)}>تعديل الخيارات</button><button className="builderNext"><Sparkles/> حفظ في مكتبتي</button></div></section>}
 </main>
}