"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Check,ChevronLeft,Clock3,School,Sparkles,UsersRound} from "lucide-react";
type Group={name:string,basis:string,task:string,minutes:string,teacher:string,whenDone:string};
const defaults:Group[]=[
 {name:"دعم موجّه",basis:"يحتاجون تعزيز متطلب أو دعمًا إضافيًا للانطلاق",task:"",minutes:"12",teacher:"ابدأ معهم بنمذجة قصيرة ثم تحقق من الفهم.",whenDone:"ينتقل إلى مهمة الإتقان بعد تحقق المؤشر."},
 {name:"المسار الأساسي",basis:"جاهزون للعمل على ناتج التعلم بالمستوى المتوقع",task:"",minutes:"15",teacher:"راقب العمل وقدم تغذية راجعة عند نقطة التحقق.",whenDone:"يختار تطبيقًا إضافيًا أو ينتقل لتحدٍ أعمق."},
 {name:"تحدٍ ممتد",basis:"أظهروا إتقانًا مبكرًا ويحتاجون عمقًا أو تعقيدًا أعلى",task:"",minutes:"15",teacher:"اطلب التبرير أو النقل إلى سياق جديد بدل زيادة الأسئلة.",whenDone:"يوثق الاستدلال أو يصمم امتدادًا جديدًا للمهمة."}
];
export default function ClassroomBuilder(){
 const [step,setStep]=useState(1),[subject,setSubject]=useState(""),[grade,setGrade]=useState(""),[lesson,setLesson]=useState(""),[goal,setGoal]=useState(""),[evidence,setEvidence]=useState(""),[total,setTotal]=useState("45"),[groups,setGroups]=useState(defaults),[transition,setTransition]=useState("إشارة موحدة ثم انتقال هادئ خلال دقيقة واحدة"),[materials,setMaterials]=useState(""),[checkpoint,setCheckpoint]=useState(""),[closure,setClosure]=useState("");
 const valid=useMemo(()=>subject.trim()&&lesson.trim()&&goal.trim(),[subject,lesson,goal]);
 function update(i:number,k:keyof Group,v:string){setGroups(x=>x.map((g,n)=>n===i?{...g,[k]:v}:g))}
 return <main className="classroomBuilder">
  <header className="tierTop"><Link href="/teacher/lab">مختبر التمايز <ArrowLeft size={14}/></Link><div><School/><b>إدارة الصف المتمايز</b></div><span>من التصميم إلى التنفيذ</span></header>
  <section className="tierIntro"><span>أداة 05 • التشغيل الصفي</span><h1>التمايز الجيد يحتاج<br/>إدارة مرنة ومقصودة.</h1><p>حوّل قرار التمايز إلى خطة حصة واضحة: لماذا تكوّنت كل مجموعة؟ ماذا ستفعل؟ أين سيكون المعلم؟ متى نتحقق من التعلم؟ وكيف ينتقل الطلاب دون إهدار وقت الحصة؟</p></section>
  <nav className="builderSteps">{["هدف ودليل","المجموعات","تشغيل الحصة","خطة التنفيذ"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
  {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>ابدأ بسبب التجميع</h2><p>المجموعة ليست تصنيفًا دائمًا للطالب؛ هي ترتيب مؤقت يخدم حاجة تعلم محددة.</p></div></div><div className="formGrid"><label>المادة<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="مثال: الرياضيات"/></label><label>الصف<input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="مثال: أول ثانوي"/></label><label className="wide">عنوان الدرس<input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="عنوان الدرس"/></label><label className="wide">ناتج التعلم<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="ما الذي ينبغي أن يصل إليه جميع الطلاب؟"/></label><label className="wide">دليل الجاهزية<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="ما البيانات أو الملاحظات التي تبرر اختلاف المسارات أو المجموعات؟"/></label></div><button className="builderNext" disabled={!valid} onClick={()=>setStep(2)}>بناء المجموعات <ChevronLeft/></button></section>}
  {step===2&&<section className="builderCard wideCard"><div className="builderHead"><span>02</span><div><h2>اجعل لكل مجموعة منطقًا ومهمة</h2><p>يمكن تغيير هذه المجموعات في الحصة التالية بمجرد تغير دليل التعلم.</p></div></div><div className="classGroups">{groups.map((g,i)=><article key={i}><div><UsersRound/><input value={g.name} onChange={e=>update(i,"name",e.target.value)}/></div><label>سبب التجميع<textarea value={g.basis} onChange={e=>update(i,"basis",e.target.value)}/></label><label>المهمة<textarea value={g.task} onChange={e=>update(i,"task",e.target.value)} placeholder="ماذا سينفذ الطلاب في هذه المجموعة؟"/></label><div className="groupMiniFields"><label>الزمن<input value={g.minutes} onChange={e=>update(i,"minutes",e.target.value)}/></label><label>دور المعلم<textarea value={g.teacher} onChange={e=>update(i,"teacher",e.target.value)}/></label></div><label>عند الانتهاء مبكرًا<textarea value={g.whenDone} onChange={e=>update(i,"whenDone",e.target.value)}/></label></article>)}</div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" onClick={()=>setStep(3)}>تشغيل الحصة <ChevronLeft/></button></div></section>}
  {step===3&&<section className="builderCard"><div className="builderHead"><span>03</span><div><h2>خطط للحركة والوقت ونقطة التحقق</h2><p>وضوح الروتين يقلل الوقت الضائع ويتيح للمعلم أن يركز على التعلم بدل إدارة الفوضى.</p></div></div><div className="operationGrid"><label><Clock3/> زمن الحصة<input value={total} onChange={e=>setTotal(e.target.value)} placeholder="45"/></label><label className="wide">آلية الانتقال بين المهام أو المحطات<textarea value={transition} onChange={e=>setTransition(e.target.value)}/></label><label className="wide">المواد والموارد<textarea value={materials} onChange={e=>setMaterials(e.target.value)} placeholder="ما الذي يجب أن يكون جاهزًا قبل بدء الحصة؟"/></label><label className="wide">نقطة التحقق المشتركة<textarea value={checkpoint} onChange={e=>setCheckpoint(e.target.value)} placeholder="ما الدليل القصير الذي ستجمعه لتقرر: يستمر، يحتاج دعمًا، أم ينتقل لتحدٍ أعلى؟"/></label><label className="wide">الإغلاق / تذكرة الخروج<textarea value={closure} onChange={e=>setClosure(e.target.value)} placeholder="كيف ستغلق الحصة وتجمع دليلًا يغذي التخطيط القادم؟"/></label></div><div className="builderActions"><button onClick={()=>setStep(2)}>السابق</button><button className="builderNext" onClick={()=>setStep(4)}>إنشاء خطة التنفيذ <ChevronLeft/></button></div></section>}
  {step===4&&<section className="builderCard wideCard reviewCard"><div className="builderHead"><span>04</span><div><h2>خطة تشغيل الحصة المتمايزة</h2><p>{subject} • {grade} • {lesson} • {total} دقيقة</p></div></div><div className="goalReview"><span>الهدف المشترك</span><b>{goal}</b><small>دليل التجميع: {evidence||"لم يحدد بعد"}</small></div><div className="classroomPlan">{groups.map((g,i)=><article key={i}><header><b>{g.name}</b><span>{g.minutes} دقيقة</span></header><small>لماذا؟</small><p>{g.basis}</p><small>المهمة</small><strong>{g.task||"لم تُكتب المهمة بعد."}</strong><small>دور المعلم</small><p>{g.teacher}</p><small>إذا انتهى مبكرًا</small><p>{g.whenDone}</p></article>)}</div><div className="opsSummary"><div><b>الانتقال</b><span>{transition}</span></div><div><b>المواد</b><span>{materials||"لم تحدد"}</span></div><div><b>نقطة التحقق</b><span>{checkpoint||"لم تحدد"}</span></div><div><b>الإغلاق</b><span>{closure||"لم يحدد"}</span></div></div><div className="classroomChecks"><Check/><span>سبب كل مجموعة واضح وقابل للتغيير.</span><Check/><span>المعلم يعرف أين يتدخل ومتى.</span><Check/><span>يوجد دليل تعلم يعيد تشكيل المجموعة القادمة.</span></div><div className="builderActions"><button onClick={()=>setStep(3)}>تعديل الخطة</button><button className="builderNext"><Sparkles/> حفظ في مكتبتي</button></div></section>}
 </main>
}