"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BarChart3,CheckCircle2,GitCompareArrows,Info,Layers3,Sparkles} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
const typeNames:any={exit_ticket:"بطاقة خروج",quiz:"اختبار قصير",observation:"ملاحظة",student_product:"منتج طالب",rubric:"Rubric",performance:"بيانات أداء",other:"أخرى"};
export default function ImpactPage(){
 const [projects,setProjects]=useState<any[]>([]),[refs,setRefs]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const [{data:p},{data:r}]=await Promise.all([s.from("teacher_differentiation_projects").select("*").order("updated_at",{ascending:false}),s.from("teacher_project_reflections").select("*").order("created_at",{ascending:true})]);setProjects(p||[]);setRefs(r||[]);setLoading(false)})()},[]);
 const families=useMemo(()=>{const roots=projects.filter(p=>!p.parent_project_id);return roots.map(root=>{const versions=projects.filter(p=>p.id===root.id||p.parent_project_id===root.id).sort((a,b)=>(a.version_no||1)-(b.version_no||1));return {root,versions}}).filter(x=>x.versions.length>0)},[projects]);
 return <main className="impactPage"><header className="tierTop"><Link href="/teacher/growth">مساري المهني <ArrowLeft size={14}/></Link><div><BarChart3/><b>قراءة أثر التمايز</b></div><span>تغيير • دليل • قرار</span></header>
 <section className="impactHero"><span>EVIDENCE BEFORE CLAIMS</span><h1>ماذا تغير؟ وماذا أظهر الدليل بعده؟</h1><p>هذه الصفحة تصف العلاقة الزمنية بين تعديل التصميم ودليل التعلم. لا تنسب التحسن سببيًا إلى أداة ما ما لم يدعم الدليل ذلك.</p></section>
 {loading?<div className="libraryEmpty">جارٍ قراءة الأدلة…</div>:<section className="impactFamilies">{families.map(({root,versions})=><article key={root.id}><header><div><span>{root.subject} • {root.grade}</span><h2>{root.lesson||root.title}</h2></div><b>{versions.length} إصدار</b></header><div className="impactVersions">{versions.map((v:any,i:number)=>{const vr=refs.filter(r=>r.project_id===v.id);const last=vr[vr.length-1];const prev=i?versions[i-1]:null;const changed=prev?["tiering","thinking","concepts","choice","operations"].filter(k=>JSON.stringify(prev.project_data?.[k]||null)!==JSON.stringify(v.project_data?.[k]||null)):[];return <div key={v.id}><div className="impactVersionTitle"><strong>V{v.version_no||1}</strong><span>{i===0?"خط الأساس":changed.length?changed.length+" مجالات تصميم تغيرت":"لا تغيير بنيوي مرصود"}</span></div>{v.improvement_hypothesis&&<p className="impactWhy">{v.version_note||"فرضية تحسين"}</p>}<div className="impactEvidenceCard">{last?<><small>{typeNames[last.evidence_type]||"دليل"} {last.evidence_label&&"• "+last.evidence_label}</small><p>{last.evidence}</p>{last.evidence_value!=null&&<b>{last.evidence_value}{last.evidence_total!=null?" / "+last.evidence_total:""}</b>}<i>القرار: {last.next_decision}</i></>:<><Info/><p>لا يوجد دليل تطبيق موثق لهذا الإصدار بعد.</p></>}</div><Link href={"/teacher/plan/"+v.id}>فتح الإصدار <ArrowLeft/></Link></div>})}</div></article>)}</section>}
 <section className="impactGuardrail"><Sparkles/><div><b>قاعدة الاستدلال</b><span>وجود تحسن بعد تعديل التصميم إشارة تستحق الفحص، وليس إثباتًا سببيًا تلقائيًا. كرر التطبيق واجمع دليلًا متسقًا قبل تعميم القرار.</span></div></section></main>}