"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Check,ChevronLeft,Layers3,Plus,Sparkles} from "lucide-react";
import {useTeacherProject} from "@/lib/useTeacherProject";
type Tier={name:string,label:string,challenge:string,support:string,task:string};
const defaults:Tier[]=[
 {name:"L1",label:"دعم موجّه",challenge:"مدخل مناسب نحو الهدف",support:"نمذجة أو دعم إضافي عند الحاجة",task:""},
 {name:"L2",label:"الإتقان",challenge:"تحقيق الهدف بالمستوى المتوقع",support:"دعم محدود واستقلالية أكبر",task:""},
 {name:"L3",label:"تحدٍ ممتد",challenge:"عمق أو تعقيد أعلى في الهدف نفسه",support:"استقلالية وتبرير ونقل للتعلم",task:""}
];
export default function TieringBuilder(){
 const {projectId,project,saveTool}=useTeacherProject(); const [saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 const [step,setStep]=useState(1),[subject,setSubject]=useState(""),[grade,setGrade]=useState(""),[lesson,setLesson]=useState(""),[goal,setGoal]=useState(""),[evidence,setEvidence]=useState("");
 const [tiers,setTiers]=useState(defaults);
 useState(()=>{});
 useMemo(()=>{if(project){setSubject(project.subject||"");setGrade(project.grade||"");setLesson(project.lesson||project.title||"");setGoal(project.learning_goal||"");setEvidence(project.readiness_evidence||"");const old=project.project_data?.tiering;if(old?.tiers)setTiers(old.tiers)}return null},[project]);
 const valid=useMemo(()=>subject.trim()&&lesson.trim()&&goal.trim(),[subject,lesson,goal]);
 function update(i:number,key:keyof Tier,value:string){setTiers(x=>x.map((t,n)=>n===i?{...t,[key]:value}:t))}
 return <main className="tierBuilder">
  <header className="tierTop"><Link href="/teacher/lab">مختبر التمايز <ArrowLeft size={14}/></Link><div><Layers3/><b>باني التدرج</b></div><span>مسودة محفوظة محليًا</span></header>
  <section className="tierIntro"><span>أداة 01 • الجاهزية والتحدي</span><h1>نفس الهدف.<br/>مسارات مختلفة نحو التقدم.</h1><p>التدرج هنا يغيّر مستوى التحدي والتعقيد، لا كمية العمل. ابدأ بهدف تعلم واحد ثم صمّم مسارات مناسبة لنقاط بداية مختلفة.</p></section>
  <nav className="builderSteps">{["الهدف","دليل الجاهزية","بناء الطبقات","مراجعة"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
  {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>ثبّت ما يجب أن يتعلمه الجميع</h2><p>لا نبدأ بتقسيم الطلاب؛ نبدأ بالهدف المشترك.</p></div></div><div className="formGrid"><label>المادة<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="مثال: الرياضيات"/></label><label>الصف<input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="مثال: أول ثانوي"/></label><label className="wide">عنوان الدرس<input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="عنوان الدرس أو المفهوم"/></label><label className="wide">ناتج التعلم<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="ما الذي ينبغي أن يفهمه الطالب أو يكون قادرًا على تطبيقه؟"/></label></div><button className="builderNext" disabled={!valid} onClick={()=>setStep(2)}>التالي: دليل الجاهزية <ChevronLeft/></button></section>}
  {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>ما الدليل الذي يحدد نقطة البداية؟</h2><p>التدرج قرار مبني على الجاهزية، وليس تصنيفًا ثابتًا للطالب.</p></div></div><label className="standalone">دليل التقييم القبلي / الملاحظة<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="صف باختصار ما الذي أظهره الطلاب: متطلب سابق، استجابة قصيرة، مهمة تشخيصية، ملاحظة..."/></label><div className="readinessHints"><div><b>يحتاج دعمًا</b><span>لم يثبت بعد المتطلب أو الفهم اللازم للانطلاق باستقلالية.</span></div><div><b>جاهز للهدف</b><span>يمتلك نقطة البداية المناسبة لتحقيق ناتج التعلم.</span></div><div><b>جاهز لتحدٍ أعلى</b><span>أظهر إتقانًا مبكرًا ويحتاج عمقًا أو تعقيدًا إضافيًا.</span></div></div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" onClick={()=>setStep(3)}>بناء الطبقات <ChevronLeft/></button></div></section>}
  {step===3&&<section className="builderCard wideCard"><div className="builderHead"><span>03</span><div><h2>ابنِ ثلاث طرق نحو الهدف نفسه</h2><p>لا تجعل L3 أسئلة أكثر؛ اجعله تفكيرًا أعمق. ولا تجعل L1 هدفًا أقل؛ وفّر له مدخلًا ودعمًا مناسبين.</p></div></div><div className="tierCards">{tiers.map((t,i)=><article key={t.name} className={"tierEdit t"+(i+1)}><div><b>{t.name}</b><input value={t.label} onChange={e=>update(i,"label",e.target.value)}/></div><label>مستوى التحدي<textarea value={t.challenge} onChange={e=>update(i,"challenge",e.target.value)}/></label><label>الدعم / الاستقلالية<textarea value={t.support} onChange={e=>update(i,"support",e.target.value)}/></label><label>المهمة الفعلية<textarea value={t.task} onChange={e=>update(i,"task",e.target.value)} placeholder="اكتب المهمة التي سينفذها الطالب..."/></label></article>)}</div><div className="builderActions"><button onClick={()=>setStep(2)}>السابق</button><button className="builderNext" onClick={()=>setStep(4)}>مراجعة التصميم <ChevronLeft/></button></div></section>}
  {step===4&&<section className="builderCard reviewCard"><div className="builderHead"><span>04</span><div><h2>فحص سريع قبل التطبيق</h2><p>{subject} • {grade} • {lesson}</p></div></div><div className="goalReview"><span>الهدف المشترك</span><b>{goal}</b></div><div className="reviewChecks"><div><Check/><span>الطبقات الثلاث تعمل نحو الهدف نفسه.</span></div><div><Check/><span>الاختلاف في التحدي والدعم، وليس مجرد كمية العمل.</span></div><div><Check/><span>اختيار الطبقة يستند إلى دليل جاهزية قابل للتحديث.</span></div></div><div className="tierReview">{tiers.map(t=><article key={t.name}><b>{t.name} • {t.label}</b><span>{t.challenge}</span><p>{t.task||"لم تُكتب المهمة بعد."}</p></article>)}</div><div className="builderActions"><button onClick={()=>setStep(3)}>تعديل الطبقات</button><button className="builderNext" disabled={saving} onClick={async()=>{setSaving(true);try{await saveTool("tiering",{tiers,evidence,updated_at:new Date().toISOString()});setSaved(true)}finally{setSaving(false)}}}><Sparkles/> {saved?"تم الحفظ":saving?"جارٍ الحفظ…":"حفظ في المشروع"}</button></div></section>}
 {projectId&&<div className="projectContextBar"><span>هذا العمل مرتبط بمشروع: <b>{project?.title||"الدرس المتمايز"}</b></span><Link href={"/teacher/library"}>مكتبتي</Link></div>}</main>
}