"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
import Link from "next/link";
import {ArrowLeft,BrainCircuit,Check,ChevronLeft,GitCompareArrows,Grid3X3,Layers3,Route,School,Sparkles} from "lucide-react";
type Need="readiness"|"thinking"|"concepts"|"choice"|"operations";
const needs=[
 {id:"readiness" as Need,icon:Layers3,title:"اختلاف الجاهزية",text:"بعض الطلاب يحتاجون دعمًا، وآخرون جاهزون لتحدٍ أعمق.",tool:"باني التدرج",href:"/teacher/lab/tiering"},
 {id:"thinking" as Need,icon:BrainCircuit,title:"اختلاف عمق التفكير",text:"أريد رفع مستوى المعالجة العقلية مع الحفاظ على وضوح الهدف.",tool:"بلوم المعدل",href:"/teacher/lab/bloom"},
 {id:"concepts" as Need,icon:GitCompareArrows,title:"تعقيد المفاهيم والعلاقات",text:"أحتاج مقارنة مفاهيم وعلاقات بدرجات مختلفة من التعقيد.",tool:"أشكال فن",href:"/teacher/lab/venn"},
 {id:"choice" as Need,icon:Grid3X3,title:"تنويع طرق التعبير والمنتج",text:"أريد خيارات مقصودة دون أن يفقد الدرس هدفه المشترك.",tool:"إكس / أو",href:"/teacher/lab/xo"},
 {id:"operations" as Need,icon:School,title:"تشغيل مجموعات أو محطات",text:"التصميم موجود، وأحتاج تحويله إلى خطة صفية قابلة للتنفيذ.",tool:"إدارة الصف",href:"/teacher/lab/classroom"}
];
export default function LessonWizard(){
 const router=useRouter(); const [saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
 const [step,setStep]=useState(1),[subject,setSubject]=useState(""),[grade,setGrade]=useState(""),[lesson,setLesson]=useState(""),[goal,setGoal]=useState(""),[evidence,setEvidence]=useState(""),[selected,setSelected]=useState<Need[]>([]);
 const valid=useMemo(()=>subject.trim()&&lesson.trim()&&goal.trim(),[subject,lesson,goal]);
 const chosen=needs.filter(n=>selected.includes(n.id));
 function toggle(id:Need){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 async function saveProject(){setSaving(true);setSaveError("");try{const s=getSupabaseBrowserClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("يلزم تسجيل الدخول لحفظ المشروع.");const {data,error}=await s.from("teacher_differentiation_projects").insert({teacher_id:user.id,title:lesson||"درس متمايز",subject,grade,lesson,learning_goal:goal,readiness_evidence:evidence,status:"draft",selected_tools:selected,project_data:{wizard:{needs:selected}}}).select("id").single();if(error)throw error;const first=route[0]?.href;if(first)router.push(first+"?project="+data.id);else router.push("/teacher/library")}catch(e:any){setSaveError(e?.message||"تعذر حفظ المشروع")}finally{setSaving(false)}}
 const route=useMemo(()=>{const order:Need[]=["readiness","thinking","concepts","choice","operations"];return order.filter(x=>selected.includes(x)).map(id=>needs.find(n=>n.id===id)!)},[selected]);
 return <main className="lessonWizard">
  <header className="tierTop"><Link href="/teacher/lab">مختبر التمايز <ArrowLeft size={14}/></Link><div><Route/><b>معالج الدرس المتمايز</b></div><span>قرار → تصميم → تنفيذ</span></header>
  <section className="wizardHero"><span>DIFFERENTIATED LESSON PATH</span><h1>لا تبدأ باختيار استراتيجية.<br/>ابدأ بسؤال: ماذا يحتاج طلابي؟</h1><p>أدخل هدف الدرس ودليل التعلم مرة واحدة، ثم ابنِ مسار الأدوات الذي يخدم الحاجة الفعلية. ليست كل حصة بحاجة إلى الأدوات الخمس.</p></section>
  <nav className="builderSteps wizardSteps">{["سياق الدرس","قراءة الحاجة","مسار التمايز","ابدأ البناء"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
  {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>ما التعلم الذي لا نريد أن نضيعه؟</h2><p>الهدف المشترك هو مرساة القرار؛ التمايز يغير نقطة الدخول أو العملية أو التحدي أو التعبير عند الحاجة.</p></div></div><div className="formGrid"><label>المادة<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="المادة"/></label><label>الصف<input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="الصف"/></label><label className="wide">عنوان الدرس<input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="عنوان الدرس"/></label><label className="wide">ناتج التعلم<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="ما الذي ينبغي أن يعرفه الطالب أو يفهمه أو يكون قادرًا على أدائه؟"/></label><label className="wide">ما الدليل المتاح عن الطلاب؟<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="تقويم قبلي، ملاحظة، عمل سابق، استجابة سريعة، اهتمامات أو احتياجات ظهرت..."/></label></div><button className="builderNext" disabled={!valid} onClick={()=>setStep(2)}>قراءة الحاجة <ChevronLeft/></button></section>}
  {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>أين يحتاج الدرس إلى تمايز؟</h2><p>اختر حاجة واحدة أو أكثر. لا توجد ضرورة لاستخدام كل الأدوات في كل درس.</p></div></div><div className="needGrid">{needs.map(n=>{const Icon=n.icon,on=selected.includes(n.id);return <button key={n.id} className={on?"active":""} onClick={()=>toggle(n.id)}><div><Icon/><i>{on&&<Check/>}</i></div><b>{n.title}</b><span>{n.text}</span><small>{n.tool}</small></button>})}</div><div className="wizardEvidence"><span>الدليل الذي سيقود القرار</span><p>{evidence||"لم تضف دليلًا بعد؛ يمكنك الرجوع وإضافته قبل اعتماد المسار."}</p></div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" disabled={!selected.length} onClick={()=>setStep(3)}>بناء المسار <ChevronLeft/></button></div></section>}
  {step===3&&<section className="builderCard"><div className="builderHead"><span>03</span><div><h2>هذا هو مسار الأدوات المقترح للدرس</h2><p>رتبناه من قرار الجاهزية وعمق التفكير إلى التعبير ثم التشغيل الصفي.</p></div></div><div className="routeMap"><div className="routeStart"><Sparkles/><b>{lesson}</b><span>{goal}</span></div>{route.map((n,i)=>{const Icon=n.icon;return <div className="routeStep" key={n.id}><i>{i+1}</i><Icon/><div><b>{n.tool}</b><span>{n.title}</span></div></div>})}<div className="routeEnd"><School/><b>خطة تعلم قابلة للتنفيذ</b><span>ثم نجمع دليلًا جديدًا يعيد تشكيل القرار القادم.</span></div></div><div className="routeRule"><b>قاعدة المعالج</b><span>استخدم أقل عدد من الأدوات التي تحقق الغرض. جودة التمايز في دقة القرار، لا في كثرة الاستراتيجيات.</span></div><div className="builderActions"><button onClick={()=>setStep(2)}>تعديل الحاجة</button><button className="builderNext" onClick={()=>setStep(4)}>اعتماد المسار <ChevronLeft/></button></div></section>}
  {step===4&&<section className="builderCard reviewCard"><div className="builderHead"><span>04</span><div><h2>ابدأ البناء من الأداة الأولى</h2><p>{subject} • {grade} • {lesson}</p></div></div><div className="goalReview"><span>الهدف المشترك</span><b>{goal}</b><small>الدليل: {evidence||"غير محدد"}</small></div><div className="launchRoute">{route.map((n,i)=>{const Icon=n.icon;return <article key={n.id}><div><i>{i+1}</i><Icon/></div><span>{n.title}</span><b>{n.tool}</b><p>{n.text}</p><Link href={n.href}>{i===0?"ابدأ من هنا":"فتح الأداة"} <ArrowLeft/></Link></article>})}</div><div className="wizardNote"><Sparkles/><div><b>المرحلة التالية في التطوير</b><span>ستنتقل بيانات الدرس تلقائيًا بين هذه الأدوات، ويُجمع ناتجها في «خطة درس متمايز» واحدة داخل مكتبة المعلم.</span></div></div><div className="wizardSaveRow">{saveError&&<span>{saveError}</span>}<button className="saveProjectButton" disabled={saving} onClick={saveProject}><Sparkles/>{saving?"جارٍ الحفظ…":"حفظ وبدء المسار"}</button></div><div className="builderActions"><button onClick={()=>setStep(3)}>مراجعة المسار</button>{route[0]&&<Link className="builderNext" href={route[0].href}>ابدأ بناء الدرس <ChevronLeft/></Link>}</div></section>}
 </main>
}