"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowRight,Target,UsersRound,AlertTriangle,CheckCircle2,Sparkles} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";

type C={id:string;name:string;subject:string;grade:string;stage:string};
type S={id:string;class_id:string;display_name:string};
type M={student_id:string;skill_id:string;state:string;score:number|null;confidence:number|null;evidence_count:number};
type K={id:string;code:string;name:string;parent_skill_id:string|null;prerequisite_skill_ids:string[]};

export default function ReadinessPage(){
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[mastery,setMastery]=useState<M[]>([]),[skills,setSkills]=useState<K[]>([]),[cid,setCid]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const {data:c}=await s.from("classes").select("id,name,subject,grade,stage").order("created_at",{ascending:false});const cs=(c||[]) as C[];setClasses(cs);if(cs[0])setCid(cs[0].id);setLoading(false)})()},[]);
 useEffect(()=>{if(!cid)return;(async()=>{const s=getSupabaseBrowserClient();const {data:st}=await s.from("students").select("id,class_id,display_name").eq("class_id",cid);const ss=(st||[]) as S[];setStudents(ss);const ids=ss.map(x=>x.id);if(!ids.length){setMastery([]);setSkills([]);return}const {data:mm}=await s.from("mastery").select("student_id,skill_id,state,score,confidence,evidence_count").in("student_id",ids);const ms=(mm||[]) as M[];setMastery(ms);const sk=[...new Set(ms.map(x=>x.skill_id))];if(!sk.length){setSkills([]);return}const {data:kk}=await s.from("skills").select("id,code,name,parent_skill_id,prerequisite_skill_ids").in("id",sk);setSkills((kk||[]) as K[])})()},[cid]);
 const stats=useMemo(()=>{const by=new Map<string,M[]>();mastery.forEach(m=>{const a=by.get(m.student_id)||[];a.push(m);by.set(m.student_id,a)});let support=0,core=0,challenge=0;students.forEach(st=>{const a=by.get(st.id)||[];const bad=a.filter(x=>x.state==="gap"||x.state==="emerging").length;const strong=a.filter(x=>x.state==="secure"||x.state==="mastered").length;if(bad>0)support++;else if(a.length&&strong===a.length)challenge++;else core++});const scored=mastery.filter(x=>x.score!=null);const readiness=scored.length?Math.round(scored.reduce((n,x)=>n+Number(x.score),0)/scored.length):0;return{support,core,challenge,readiness}},[students,mastery]);
 const skillStats=useMemo(()=>skills.map(k=>{const a=mastery.filter(x=>x.skill_id===k.id);const gap=a.filter(x=>x.state==="gap"||x.state==="emerging").length;const secure=a.filter(x=>x.state==="secure"||x.state==="mastered").length;return{...k,total:a.length,gap,secure}}).sort((a,b)=>b.gap-a.gap),[skills,mastery]);
 const studentGroups=useMemo(()=>students.map(st=>{const a=mastery.filter(x=>x.student_id===st.id);const weak=a.filter(x=>x.state==="gap"||x.state==="emerging");const strong=a.filter(x=>x.state==="secure"||x.state==="mastered");const group=weak.length?"support":a.length&&strong.length===a.length?"challenge":"core";const weakSkills=weak.map(x=>skills.find(k=>k.id===x.skill_id)?.name).filter(Boolean);const prereq=[...new Set(weak.flatMap(x=>skills.find(k=>k.id===x.skill_id)?.prerequisite_skill_ids||[]))].map(id=>skills.find(k=>k.id===id)?.name).filter(Boolean);return{...st,group,weakSkills,prereq}}),[students,mastery,skills]);
 const groupInfo={support:{title:"دعم موجّه",level:"L1",note:"معالجة فجوة قبل الانتقال"},core:{title:"المسار الأساسي",level:"L2",note:"بناء الهدف الحالي"},challenge:{title:"تحدٍ ممتد",level:"L3",note:"تعميق ونقل أثر التعلم"}} as const;
 if(loading)return <main className="roleGate"><div className="roleGateCard"><h1>جارٍ قراءة جاهزية الفصل…</h1></div></main>;
 return <main className="readinessPage">
  <header className="readinessTop"><Link href="/"><ArrowRight/> رحلة اليوم</Link><div><span>PART 2 • LEARNING OPERATIONS</span><h1>جاهزية الفصل وخريطة المهارات</h1><p>قراءة مباشرة من شواهد الإتقان الحالية؛ المجموعات مرنة وتتغير مع كل دليل تعلم جديد.</p></div><select value={cid} onChange={e=>setCid(e.target.value)}>{classes.map(c=><option key={c.id} value={c.id}>{c.name} • {c.subject}</option>)}</select></header>
  {!classes.length?<section className="readinessEmpty"><UsersRound/><h2>لا توجد فصول بعد</h2><p>أضف الفصل والطلاب أولًا، ثم ستظهر خريطة الجاهزية هنا تلقائيًا.</p></section>:<>
  <section className="readinessKpis"><article><UsersRound/><div><b>{students.length}</b><span>طالبًا</span></div></article><article><Target/><div><b>{stats.readiness}%</b><span>متوسط الجاهزية من الأدلة المسجلة</span></div></article><article><AlertTriangle/><div><b>{stats.support}</b><span>دعم موجّه</span></div></article><article><Sparkles/><div><b>{stats.challenge}</b><span>تحدٍ ممتد</span></div></article></section>
  <section className="readinessGroups"><article className="peach"><b>دعم موجّه</b><strong>{stats.support}</strong><p>لديهم فجوة أو مهارة ناشئة في دليل مسجل.</p></article><article className="mint"><b>المسار الأساسي</b><strong>{stats.core}</strong><p>يتابعون الهدف الحالي دون فجوة ظاهرة في البيانات.</p></article><article className="violet"><b>تحدٍ ممتد</b><strong>{stats.challenge}</strong><p>الأدلة الحالية تشير إلى Secure/Mastered في المهارات المقاسة.</p></article></section>
  <section className="readinessSurface"><header><div><span>SKILL MAP</span><h2>أين تتركز الفجوات؟</h2></div><small>{mastery.length} شاهد إتقان مسجل</small></header>{!skillStats.length?<div className="readinessEmpty small"><Target/><h3>لا توجد نتائج إتقان لهذا الفصل بعد</h3><p>لن نخمن الجاهزية. ستظهر الخريطة بعد إدخال أول تشخيص أو تقويم.</p></div>:<div className="skillRows">{skillStats.map(k=><div key={k.id} className="skillRow"><div><b>{k.name}</b><span>{k.code}</span></div><div className="skillBar"><i style={{width:(k.total?Math.round(k.secure/k.total*100):0)+"%"}}/></div><div className="skillCounts"><span className="gap">{k.gap} يحتاج دعمًا</span><span className="ok"><CheckCircle2/> {k.secure} متقن</span></div></div>)}</div>}</section>
  <section className="readinessSurface"><header><div><span>FLEXIBLE GROUPS</span><h2>المجموعات المرنة ومسار الحصة</h2></div><small>تتغير تلقائيًا مع الدليل التالي</small></header><div className="studentGroupColumns">{(["support","core","challenge"] as const).map(g=><article key={g}><header><div><b>{groupInfo[g].title}</b><span>{groupInfo[g].note}</span></div><strong>{groupInfo[g].level}</strong></header>{studentGroups.filter(x=>x.group===g).map(st=><div className="studentGroupRow" key={st.id}><b>{st.display_name}</b>{st.weakSkills.length>0&&<span>فجوة: {st.weakSkills.slice(0,2).join("، ")}</span>}{st.prereq.length>0&&<small>راجع متطلبًا سابقًا: {st.prereq.slice(0,2).join("، ")}</small>}</div>)}{!studentGroups.some(x=>x.group===g)&&<p className="groupNoData">لا يوجد طلاب في هذا المسار وفق الأدلة الحالية.</p>}</article>)}</div></section>
  </>}
 </main>
}