"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {ArrowLeft,Check,ChevronLeft,Lightbulb,RefreshCw,Sparkles} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
export default function ReflectPage(){
 const {id}=useParams<{id:string}>(),router=useRouter(); const [p,setP]=useState<any>(null),[step,setStep]=useState(1),[evidence,setEvidence]=useState(""),[worked,setWorked]=useState(""),[needs,setNeeds]=useState(""),[response,setResponse]=useState(""),[decision,setDecision]=useState(""),[confidence,setConfidence]=useState(3),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const {data}=await s.from("teacher_differentiation_projects").select("*").eq("id",id).single();setP(data)})()},[id]);
 async function save(){setSaving(true);try{const s=getSupabaseBrowserClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("يلزم تسجيل الدخول");const {error}=await s.from("teacher_project_reflections").insert({project_id:id,teacher_id:user.id,evidence,worked,needs_change:needs,student_response:response,next_decision:decision,confidence});if(error)throw error;await s.from("teacher_differentiation_projects").update({status:"applied",updated_at:new Date().toISOString()}).eq("id",id);router.push("/teacher/plan/"+id)}finally{setSaving(false)}}
 return <main className="reflectionPage"><header className="tierTop"><Link href={"/teacher/plan/"+id}>خطة الدرس <ArrowLeft size={14}/></Link><div><RefreshCw/><b>ما بعد التطبيق</b></div><span>دليل → تأمل → قرار</span></header>
 <section className="reflectionHero"><span>REFLECT • ADAPT • GROW</span><h1>{p?.title||"تأمل الممارسة"}</h1><p>لا نقيس نجاح التمايز بجمال الخطة، بل بما كشفه تعلم الطلاب وما سنغيره بناءً على هذا الدليل.</p></section>
 <nav className="builderSteps">{["الدليل","قراءة الاستجابة","القرار القادم"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
 {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>ماذا أظهر تعلم الطلاب؟</h2><p>سجل دليلًا يمكن الاستناد إليه: منتج، تذكرة خروج، ملاحظة، أداء أو نتيجة تحقق.</p></div></div><label className="reflectField">دليل ما بعد الحصة<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="ما الدليل الذي جمعته؟ وماذا يقول عن تحقق ناتج التعلم؟"/></label><div className="confidence"><span>ثقتي في كفاية الدليل</span>{[1,2,3,4,5].map(n=><button className={confidence===n?"active":""} onClick={()=>setConfidence(n)} key={n}>{n}</button>)}</div><button className="builderNext" disabled={!evidence.trim()} onClick={()=>setStep(2)}>قراءة الاستجابة <ChevronLeft/></button></section>}
 {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>ما الذي حدث فعلًا أثناء التعلم؟</h2><p>افصل بين ما نجح وما يحتاج تعديلًا، وسجل استجابة الطلاب بدل الاكتفاء بانطباع عام.</p></div></div><div className="reflectGrid"><label>ما الذي نجح؟<textarea value={worked} onChange={e=>setWorked(e.target.value)} placeholder="أي قرار أو أداة أو تنظيم دعم التعلم؟"/></label><label>ما الذي يحتاج تعديلًا؟<textarea value={needs} onChange={e=>setNeeds(e.target.value)} placeholder="أين ظهرت صعوبة أو فجوة أو وقت ضائع؟"/></label><label className="wide">استجابة الطلاب<textarea value={response} onChange={e=>setResponse(e.target.value)} placeholder="ماذا لاحظت في المشاركة، الاستقلالية، جودة المنتج أو مستوى التفكير؟"/></label></div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" onClick={()=>setStep(3)}>اتخاذ القرار <ChevronLeft/></button></div></section>}
 {step===3&&<section className="builderCard reviewCard"><div className="builderHead"><span>03</span><div><h2>حوّل التأمل إلى قرار</h2><p>التأمل المهني يكتمل عندما يغيّر التصميم أو التنفيذ القادم.</p></div></div><label className="reflectField">قراري للحصة أو النسخة القادمة<textarea value={decision} onChange={e=>setDecision(e.target.value)} placeholder="سأستمر في... / سأغير... / سأعيد تجميع... / سأرفع التحدي لـ..."/></label><div className="reflectionCycle"><div><Check/><b>الدليل</b><span>{evidence}</span></div><div><Lightbulb/><b>التعلم المهني</b><span>{worked||needs||"دوّن ما تعلمته من التطبيق."}</span></div><div><RefreshCw/><b>التعديل القادم</b><span>{decision||"حدد قرارًا واضحًا."}</span></div></div><button className="saveReflection" disabled={saving||!decision.trim()} onClick={save}><Sparkles/>{saving?"جارٍ الحفظ…":"حفظ التأمل وإغلاق دورة التطبيق"}</button></section>}
 </main>
}