"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BookOpenCheck,BrainCircuit,CheckCircle2,Compass,FileText,Layers3,Printer,RefreshCw,Sparkles,Target} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
export default function PracticePortfolio(){
 const [profile,setProfile]=useState<any>(null),[projects,setProjects]=useState<any[]>([]),[refs,setRefs]=useState<any[]>([]),[cycles,setCycles]=useState<any[]>([]),[reviews,setReviews]=useState<any[]>([]),[loading,setLoading]=useState(true),[period,setPeriod]=useState("all");
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const [{data:pr},{data:p},{data:r},{data:c},{data:rv}]=await Promise.all([s.from("profiles").select("full_name").eq("id",user.id).maybeSingle(),s.from("teacher_differentiation_projects").select("*").order("created_at",{ascending:false}),s.from("teacher_project_reflections").select("*").order("created_at",{ascending:false}),s.from("teacher_coaching_cycles").select("*").order("created_at",{ascending:false}),s.from("teacher_coaching_reviews").select("*").order("created_at",{ascending:false})]);setProfile(pr);setProjects(p||[]);setRefs(r||[]);setCycles(c||[]);setReviews(rv||[]);setLoading(false)})()},[]);
 const cutoff=period==="all"?0:Date.now()-Number(period)*86400000; const visibleProjects=projects.filter(x=>!cutoff||new Date(x.created_at).getTime()>=cutoff),visibleRefs=refs.filter(x=>!cutoff||new Date(x.created_at).getTime()>=cutoff),visibleCycles=cycles.filter(x=>!cutoff||new Date(x.created_at).getTime()>=cutoff); const applied=visibleProjects.filter(x=>x.status==="applied").length,completed=visibleCycles.filter(x=>x.status==="completed").length;
 const evidence=useMemo(()=>visibleProjects.slice(0,10),[projects,period]);
 return <main className="portfolioPage">
  <header className="tierTop noPrint"><Link href="/teacher/growth">مساري المهني <ArrowLeft size={14}/></Link><div><FileText/><b>ملف الممارسة المهنية</b></div><div className="portfolioActions"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">كل الفترة</option><option value="90">آخر 90 يومًا</option><option value="180">آخر 6 أشهر</option><option value="365">آخر سنة</option></select><button onClick={()=>window.print()}><Printer/> طباعة / PDF</button></div></header>
  {loading?<div className="libraryEmpty">جارٍ بناء ملف الممارسة…</div>:<>
  <section className="portfolioCover"><span>PROFESSIONAL PRACTICE PORTFOLIO</span><h1>ملف الممارسة المهنية</h1><h2>{profile?.full_name||"المعلم"}</h2><p>سجل حيّ يربط التصميم بالتطبيق، والدليل بالتأمل، والتأمل بقرار تطوير مهني جديد.</p><div className="portfolioNumbers"><div><b>{visibleProjects.length}</b><span>تصميم</span></div><div><b>{applied}</b><span>تطبيق موثق</span></div><div><b>{visibleRefs.length}</b><span>تأمل</span></div><div><b>{visibleCycles.length}</b><span>دورة كوتشينق</span></div><div><b>{completed}</b><span>هدف تحقق</span></div></div></section>
  <section className="portfolioSection"><header><BookOpenCheck/><div><span>01</span><h2>شواهد التصميم والتطبيق</h2><p>نماذج من الدروس التي انتقلت من قرار التمايز إلى ممارسة قابلة للتتبع.</p></div></header><div className="portfolioProjects">{evidence.map(p=>{const r=refs.filter(x=>x.project_id===p.id);const used=["tiering","thinking","concepts","choice","operations"].filter(k=>p.project_data?.[k]).length;return <article key={p.id}><div><b>{p.title}</b><small>{[p.subject,p.grade].filter(Boolean).join(" • ")}</small></div><p>{p.learning_goal}</p>{p.version_no>1&&<div className="portfolioVersion"><b>V{p.version_no}</b><span>{p.version_note||"نسخة محسنة"}</span></div>}<footer><span><Layers3/> {used} أدوات</span><span><RefreshCw/> {r.length} دورات تحسين</span><Link className="noPrint" href={"/teacher/plan/"+p.id}>فتح الشاهد</Link></footer></article>})}</div></section>
  <section className="portfolioSection"><header><BrainCircuit/><div><span>02</span><h2>التأمل المبني على الدليل</h2><p>قرارات مهنية خرجت من قراءة تعلم الطلاب بعد التطبيق.</p></div></header><div className="portfolioReflections">{visibleRefs.slice(0,8).map(r=>{const p=projects.find(x=>x.id===r.project_id);return <article key={r.id}><header><b>{p?.title||"درس متمايز"}</b><small>{new Date(r.created_at).toLocaleDateString("ar-SA")}</small></header><div><span>الدليل</span><p>{r.evidence}</p></div><div><span>القرار التالي</span><p>{r.next_decision}</p></div></article>})}</div></section>
  <section className="portfolioSection"><header><Compass/><div><span>03</span><h2>أهداف التطوير والكوتشينق</h2><p>من التأمل إلى هدف وإجراء ودليل نجاح ثم مراجعة.</p></div></header><div className="portfolioCoaching">{visibleCycles.map(c=>{const rs=reviews.filter(x=>x.cycle_id===c.id);const last=rs[0];return <article key={c.id}><header><Target/><b>{c.focus}</b><span className={c.status}>{c.status==="completed"?"مكتمل":"نشط"}</span></header><p>{c.development_goal}</p><div><small>الإجراء</small><span>{c.action_step}</span></div><div><small>دليل النجاح</small><span>{c.success_evidence}</span></div>{last&&<div className="portfolioOutcome"><CheckCircle2/><span>{last.outcome==="achieved"?"تحقق الهدف":last.outcome==="continue"?"استمرار دورة التطوير":"تم تعديل المسار"} — {last.next_step}</span></div>}</article>})}</div></section>
  <section className="portfolioClosing"><Sparkles/><div><span>قراءة الملف</span><h2>الممارسة المهنية سلسلة تعلم، وليست مجموعة مرفقات.</h2><p>كل شاهد في هذا الملف مرتبط بقرار تصميم أو تطبيق أو تأمل أو تطوير. لذلك يمكن استخدامه في جلسة كوتشينق أو مراجعة ذاتية دون تحويله إلى درجة أداء آلية.</p></div></section>
  </>}</main>
}