"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {ArrowLeft,Check,ChevronLeft,RefreshCw,Sparkles,Target} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
const outcomes=[
 {id:"achieved",title:"تحقق الهدف",note:"الدليل يشير إلى أن التغيير المقصود أصبح ظاهرًا في الممارسة أو تعلم الطلاب."},
 {id:"continue",title:"يحتاج دورة أخرى",note:"الاتجاه مناسب، لكننا نحتاج تطبيقًا أو دليلًا إضافيًا قبل الإغلاق."},
 {id:"revise",title:"تعديل الهدف",note:"الدليل الجديد غيّر فهمنا للحاجة، ولذلك نعيد صياغة الهدف أو الإجراء."}
];
export default function CoachingReview(){
 const {id}=useParams<{id:string}>(),router=useRouter(); const [cycle,setCycle]=useState<any>(null),[step,setStep]=useState(1),[tried,setTried]=useState(true),[evidence,setEvidence]=useState(""),[impact,setImpact]=useState(""),[outcome,setOutcome]=useState(""),[next,setNext]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const {data}=await s.from("teacher_coaching_cycles").select("*").eq("id",id).single();setCycle(data)})()},[id]);
 async function save(){setSaving(true);try{const s=getSupabaseBrowserClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("يلزم تسجيل الدخول");const {error}=await s.from("teacher_coaching_reviews").insert({cycle_id:id,teacher_id:user.id,tried_action:tried,observed_evidence:evidence,impact_reflection:impact,outcome,next_step:next});if(error)throw error;await s.from("teacher_coaching_cycles").update({status:outcome==="achieved"?"completed":"active",updated_at:new Date().toISOString()}).eq("id",id);router.push("/teacher/growth")}finally{setSaving(false)}}
 return <main className="coachingPage"><header className="tierTop"><Link href="/teacher/growth">مساري المهني <ArrowLeft size={14}/></Link><div><RefreshCw/><b>مراجعة هدف التطوير</b></div><span>جرّبت • لاحظت • قررت</span></header>
 <section className="coachHero reviewGoalHero"><span>REVIEW THE CHANGE</span><h1>{cycle?.focus||"هدف التطوير"}</h1><p>{cycle?.development_goal||"جارٍ تحميل الهدف…"}</p>{cycle&&<div className="reviewGoalMeta"><span>الإجراء المتفق عليه</span><b>{cycle.action_step}</b><span>دليل النجاح المتوقع</span><b>{cycle.success_evidence}</b></div>}</section>
 <nav className="builderSteps">{["التجربة","الدليل والأثر","القرار"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
 {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>هل جُرّب الإجراء المتفق عليه؟</h2><p>ابدأ بما حدث فعليًا، لا بما كان مخططًا له.</p></div></div><div className="binaryChoice"><button className={tried?"active":""} onClick={()=>setTried(true)}><Check/><b>نعم، جُرّب</b><span>سأراجع الآن ما نتج عنه.</span></button><button className={!tried?"active":""} onClick={()=>setTried(false)}><RefreshCw/><b>لم يُجرّب بعد</b><span>سأوثق السبب والخطوة التالية بدل إغلاق الهدف.</span></button></div><button className="builderNext" onClick={()=>setStep(2)}>قراءة الدليل <ChevronLeft/></button></section>}
 {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>{tried?"ماذا حدث بعد التجربة؟":"ما الذي منع التطبيق؟"}</h2><p>{tried?"قارن الدليل بما كنت تتوقع رؤيته عند صياغة هدف التطوير.":"عدم التطبيق معلومة مهنية أيضًا؛ سجلها وحدد ما يحتاج أن يتغير."}</p></div></div><div className="reflectGrid"><label>الدليل الذي لاحظته<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder={tried?"ماذا رأيت في تعلم الطلاب أو ممارستك؟":"ما الدليل أو الظرف الذي يفسر عدم التطبيق؟"}/></label><label>قراءتي للأثر<textarea value={impact} onChange={e=>setImpact(e.target.value)} placeholder="ما الذي تغير؟ وما الذي بقي كما هو؟"/></label></div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" disabled={!evidence.trim()} onClick={()=>setStep(3)}>اتخاذ القرار <ChevronLeft/></button></div></section>}
 {step===3&&<section className="builderCard reviewCard"><div className="builderHead"><span>03</span><div><h2>ماذا نفعل بهذا الهدف الآن؟</h2><p>اختر القرار الذي يدعمه الدليل، ثم اكتب الخطوة التالية بوضوح.</p></div></div><div className="outcomeChoices">{outcomes.map(o=><button key={o.id} className={outcome===o.id?"active":""} onClick={()=>setOutcome(o.id)}><Target/><b>{o.title}</b><span>{o.note}</span></button>)}</div><label className="reflectField">الخطوة التالية<textarea value={next} onChange={e=>setNext(e.target.value)} placeholder={outcome==="achieved"?"كيف ستحافظ على الممارسة أو تنقلها لسياق جديد؟":outcome==="revise"?"ما الهدف أو الإجراء المعدل؟":"ما الذي ستجربه في الدورة التالية؟"}/></label><button className="saveReflection" disabled={saving||!outcome||!next.trim()} onClick={save}><Sparkles/>{saving?"جارٍ الحفظ…":"حفظ نتيجة المراجعة"}</button></section>}
 </main>
}