"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {ArrowLeft,BrainCircuit,Check,Copy,GitCompareArrows,Grid3X3,Layers3,Printer,School,Sparkles} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
export default function IntegratedPlan(){
 const {id}=useParams<{id:string}>(),router=useRouter(); const [p,setP]=useState<any>(null),[reflections,setReflections]=useState<any[]>([]),[versions,setVersions]=useState<any[]>([]),[familyRefs,setFamilyRefs]=useState<any[]>([]),[previous,setPrevious]=useState<any>(null),[loading,setLoading]=useState(true),[creatingVersion,setCreatingVersion]=useState(false);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const {data}=await s.from("teacher_differentiation_projects").select("*").eq("id",id).single();setP(data);const {data:rs}=await s.from("teacher_project_reflections").select("*").eq("project_id",id).order("created_at",{ascending:false});setReflections(rs||[]);const root=(data as any)?.parent_project_id||id;const {data:vs}=await s.from("teacher_differentiation_projects").select("id,title,version_no,parent_project_id,status,version_note,updated_at").or("id.eq."+root+",parent_project_id.eq."+root).order("version_no",{ascending:true});setVersions(vs||[]);const familyIds=(vs||[]).map((v:any)=>v.id);if(familyIds.length){const {data:fr}=await s.from("teacher_project_reflections").select("*").in("project_id",familyIds).order("created_at",{ascending:true});setFamilyRefs(fr||[])}if((data as any)?.version_no>1){const prev=(vs||[]).filter((v:any)=>(v.version_no||1)<(data as any).version_no).sort((a:any,b:any)=>b.version_no-a.version_no)[0];if(prev){const {data:fullPrev}=await s.from("teacher_differentiation_projects").select("*").eq("id",prev.id).single();setPrevious(fullPrev)}}setLoading(false)})()},[id]);
 if(loading)return <main className="integratedPlan"><div className="libraryEmpty">جارٍ بناء خطة الدرس…</div></main>;
 if(!p)return <main className="integratedPlan"><div className="libraryEmpty">تعذر العثور على المشروع.</div></main>;
 async function createImprovedVersion(){setCreatingVersion(true);try{const s=getSupabaseBrowserClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("يلزم تسجيل الدخول");const latest=reflections[0];const root=p.parent_project_id||p.id;const next=Math.max(p.version_no||1,...versions.map((v:any)=>v.version_no||1))+1;const hypothesis=latest?["الدليل: "+(latest.evidence||"—"),"يحتاج تعديلًا: "+(latest.needs_change||"—"),"القرار القادم: "+(latest.next_decision||"—")].join("\n"):"نسخة تطويرية مبنية على التصميم السابق؛ لم يسجل تأمل سابق لهذا الإصدار.";const {data,error}=await s.from("teacher_differentiation_projects").insert({teacher_id:user.id,title:p.title.replace(/ — V\\d+$/,"")+" — V"+next,subject:p.subject,grade:p.grade,lesson:p.lesson,learning_goal:p.learning_goal,readiness_evidence:p.readiness_evidence,status:"draft",selected_tools:p.selected_tools||[],project_data:p.project_data||{},parent_project_id:root,version_no:next,version_note:latest?.next_decision||"نسخة محسنة",improvement_hypothesis:hypothesis,source_reflection_id:latest?.id||null}).select("id").single();if(error)throw error;router.push("/teacher/plan/"+data.id)}catch(e:any){alert(e?.message||"تعذر إنشاء النسخة المحسنة. حاول مرة أخرى.")}finally{setCreatingVersion(false)}}
 const d=p.project_data||{}, tools=[
  ["readiness","التدرج",Layers3,"tiering"],["thinking","بلوم المعدل",BrainCircuit,"bloom"],["concepts","أشكال فن",GitCompareArrows,"venn"],["choice","إكس / أو",Grid3X3,"xo"],["operations","إدارة الصف",School,"classroom"]
 ] as const;
 return <main className="integratedPlan">
  <header className="tierTop noPrint"><Link href="/teacher/library">مكتبتي <ArrowLeft size={14}/></Link><div><Sparkles/><b>خطة الدرس المتمايز</b></div><div className="planTopActions"><button onClick={createImprovedVersion} disabled={creatingVersion}><Copy/> {creatingVersion?"جارٍ الإنشاء…":"إنشاء V"+(Math.max(p.version_no||1,...versions.map((v:any)=>v.version_no||1))+1)+" محسنة"}</button><Link href={"/teacher/reflect/"+id}><Sparkles/> تسجيل ما بعد التطبيق</Link><button onClick={()=>window.print()}><Printer/> طباعة / PDF</button></div></header>
  <section className="planCover"><span>DIFFERENTIATED LESSON PLAN</span><h1>{p.title}</h1><p>{[p.subject,p.grade].filter(Boolean).join(" • ")}</p><div><small>ناتج التعلم المشترك</small><b>{p.learning_goal}</b></div><div><small>دليل الجاهزية والقرار</small><b>{p.readiness_evidence||"لم يحدد"}</b></div></section>
  {versions.length>1&&<ImpactJourney versions={versions} reflections={familyRefs}/>}
  {versions.length>1&&<section className="versionJourney"><header><span>EVOLUTION</span><h2>سلسلة تطور الدرس</h2><p>كل إصدار يحتفظ بتصميمه ودليله؛ افتح أي نسخة لمقارنة مسار التحسين عبر الزمن.</p></header><div>{versions.map((v:any)=><Link className={v.id===id?"current":""} href={"/teacher/plan/"+v.id} key={v.id}><b>V{v.version_no||1}</b><span>{v.status==="applied"?"مطبق":v.status==="ready"?"جاهز":"مسودة"}</span><small>{v.version_note||new Date(v.updated_at).toLocaleDateString("ar-SA")}</small></Link>)}</div></section>}
  {previous&&<VersionComparison current={p} previous={previous}/>}
  {p.improvement_hypothesis&&<section className="improvementHypothesis"><header><Sparkles/><div><span>فرضية التحسين • V{p.version_no}</span><h2>لماذا أنشأنا هذه النسخة؟</h2></div></header><pre>{p.improvement_hypothesis}</pre>{p.source_reflection_id&&<small>هذه الفرضية مرتبطة بتأمل موثق من الإصدار السابق.</small>}</section>}
  <section className="planProgress noPrint">{tools.filter(t=>(p.selected_tools||[]).includes(t[0])).map(([key,label,Icon,route])=><div className={d[key]?"complete":""} key={key}><Icon/><span>{label}</span>{d[key]?<Check/>:<Link href={"/teacher/lab/"+route+"?project="+id}>إكمال</Link>}</div>)}</section>
  {d.tiering&&<PlanSection icon={<Layers3/>} n="01" title="التدرج حسب الجاهزية"><div className="planTierGrid">{(d.tiering.tiers||[]).map((x:any,i:number)=><article key={i}><span>L{i+1}</span><h3>{x.title||x.name||["دعم موجّه","الإتقان","تحدٍ ممتد"][i]}</h3><p>{x.task||x.challenge||"—"}</p><small>{x.support||x.scaffold||""}</small></article>)}</div></PlanSection>}
  {d.thinking&&<PlanSection icon={<BrainCircuit/>} n="02" title="عمق التفكير ودليل التعلم"><div className="planRows">{(d.thinking.rows||[]).filter((x:any)=>x.process||x.product).map((x:any)=><article key={x.level}><b>{x.level}</b><span>{x.process||"—"}</span><i>{x.product||"—"}</i></article>)}</div></PlanSection>}
  {d.concepts&&<PlanSection icon={<GitCompareArrows/>} n="03" title="المقارنة وتعقيد المفاهيم"><div className="planSimple"><b>{(d.concepts.concepts||[]).slice(0,d.concepts.count).filter(Boolean).join(" × ")}</b><p>{d.concepts.prompt}</p><small>دليل التعلم: {d.concepts.evidence||"—"}</small></div></PlanSection>}
  {d.choice&&<PlanSection icon={<Grid3X3/>} n="04" title="لوحة الاختيار المقصود"><div className="planChoices">{(d.choice.choices||[]).slice(0,d.choice.size).filter((x:any)=>x.title||x.product).map((x:any,i:number)=><article key={i}><span>{x.mode||"اختيار"}</span><b>{x.title}</b><p>{x.product}</p><small>{x.challenge}</small></article>)}</div><div className="planRule">قاعدة الاختيار: {d.choice.rule}</div></PlanSection>}
  {d.operations&&<PlanSection icon={<School/>} n="05" title="خطة التشغيل الصفي"><div className="planTierGrid">{(d.operations.groups||[]).map((g:any,i:number)=><article key={i}><span>{g.minutes} دقيقة</span><h3>{g.name}</h3><p>{g.task||"—"}</p><small>دور المعلم: {g.teacher}</small></article>)}</div><div className="opsSummary"><div><b>الانتقال</b><span>{d.operations.transition}</span></div><div><b>نقطة التحقق</b><span>{d.operations.checkpoint||"—"}</span></div><div><b>الإغلاق</b><span>{d.operations.closure||"—"}</span></div><div><b>المواد</b><span>{d.operations.materials||"—"}</span></div></div></PlanSection>}
  <section className="planReflection"><span>بعد التطبيق</span><h2>الدليل الجديد هو بداية القرار القادم</h2><p>دوّن ما أظهره الطلاب من تعلم، ثم أعد تشكيل الدعم أو التحدي أو المجموعات في الحصة التالية بدل تثبيت الطلاب في مسارات دائمة.</p><Link className="noPrint reflectCta" href={"/teacher/reflect/"+id}>{reflections.length?"إضافة تأمل جديد":"تسجيل دليل ما بعد الحصة"} <ArrowLeft/></Link></section>{reflections.length>0&&<section className="reflectionHistory"><header><span>سجل الممارسة</span><h2>كيف تطور هذا الدرس؟</h2></header>{reflections.map((r:any,i:number)=><article key={r.id}><div><b>تطبيق {reflections.length-i}</b><small>{new Date(r.created_at).toLocaleDateString("ar-SA")}</small></div><p><strong>الدليل</strong>{r.evidence}</p><p><strong>ما نجح</strong>{r.worked||"—"}</p><p><strong>يحتاج تعديلًا</strong>{r.needs_change||"—"}</p><p className="decision"><strong>القرار القادم</strong>{r.next_decision}</p></article>)}</section>}
 </main>
}
function ImpactJourney({versions,reflections}:{versions:any[],reflections:any[]}){
 return <section className="impactJourney"><header><span>IMPROVEMENT EVIDENCE</span><h2>رحلة التحسين والدليل عبر الزمن</h2><p>هذه الخريطة لا تفترض أن الإصدار الأحدث أفضل؛ بل تعرض التعديل والدليل الذي ظهر بعد تطبيق كل نسخة.</p></header><div className="impactFlow">{versions.map((v:any,i:number)=>{const rs=reflections.filter((r:any)=>r.project_id===v.id);const last=rs[rs.length-1];return <div className="impactNode" key={v.id}><Link href={"/teacher/plan/"+v.id}><b>V{v.version_no||1}</b><span>{v.version_note||"التصميم"}</span></Link><div className="impactEvidence"><small>{rs.length?"دليل بعد التطبيق":"بانتظار دليل التطبيق"}</small>{last?<><p>{last.evidence||"—"}</p><i>{last.next_decision||"—"}</i></>:<p>لا يوجد تأمل موثق لهذه النسخة بعد.</p>}</div>{i<versions.length-1&&<strong>←</strong>}</div>})}</div><footer><Sparkles/><span><b>قاعدة القراءة:</b> نبحث عن نمط: ما التعديل الذي أجريناه؟ ماذا أظهر الطلاب بعده؟ وما القرار الذي نتج؟</span></footer></section>
}
function VersionComparison({current,previous}:{current:any,previous:any}){
 const a=previous.project_data||{},b=current.project_data||{};
 const specs=[
  ["tiering","التدرج والجاهزية","مستويات الدعم والتحدي",(x:any)=>JSON.stringify(x?.tiers||[])],
  ["thinking","عمق التفكير","عمليات التفكير ونواتجها",(x:any)=>JSON.stringify(x?.rows||[])],
  ["concepts","أشكال فن","المفاهيم والمهمة والدليل",(x:any)=>JSON.stringify({count:x?.count,concepts:x?.concepts,prompt:x?.prompt,evidence:x?.evidence})],
  ["choice","الاختيار المقصود","الخيارات وقاعدة الاختيار",(x:any)=>JSON.stringify({size:x?.size,rule:x?.rule,choices:x?.choices})],
  ["operations","التشغيل الصفي","المجموعات والزمن ونقاط التحقق",(x:any)=>JSON.stringify(x||{})]
 ] as const;
 const changes=specs.map(([key,title,desc,pack])=>({key,title,desc,before:!!a[key],after:!!b[key],changed:pack(a[key])!==pack(b[key])}));
 const changed=changes.filter(x=>x.changed).length;
 return <section className="versionCompare"><header><div><span>VERSION COMPARISON</span><h2>ماذا تغير من V{previous.version_no||1} إلى V{current.version_no||1}؟</h2><p>المقارنة تصف التغيير في التصميم؛ أثر هذا التغيير يُحكم عليه من دليل التطبيق اللاحق.</p></div><b>{changed}<small>مجالات تغيرت</small></b></header><div className="compareGrid">{changes.map(x=><article className={x.changed?"changed":"same"} key={x.key}><i>{x.changed?"تغيّر":"لم يتغير"}</i><b>{x.title}</b><span>{x.desc}</span><small>{!x.before&&x.after?"أضيف في هذه النسخة":x.before&&!x.after?"أزيل من هذه النسخة":x.changed?"تم تعديل بنية الأداة أو محتواها":"احتفظ التصميم بالبنية السابقة"}</small></article>)}</div>{current.improvement_hypothesis&&<div className="compareEvidence"><Sparkles/><div><b>لماذا حدث التغيير؟</b><span>{current.version_note||"فرضية تحسين مرتبطة بالدليل السابق"}</span></div></div>}</section>
}
function PlanSection({icon,n,title,children}:{icon:any,n:string,title:string,children:any}){return <section className="planSection"><header><div>{icon}<span>{n}</span></div><h2>{title}</h2></header>{children}</section>}
