"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useTeacherProject} from "@/lib/useTeacherProject";
import {ArrowLeft,Check,ChevronLeft,GitCompareArrows,Sparkles} from "lucide-react";
const modes=[
 {n:1,title:"مفهوم واحد",note:"استكشاف خصائص مفهوم واحد وتنظيم عناصره."},
 {n:2,title:"مفهومان",note:"مقارنة أوجه التشابه والاختلاف بين مفهومين."},
 {n:3,title:"ثلاثة مفاهيم",note:"تحليل علاقات مشتركة ومتقاطعة أكثر تعقيدًا."},
 {n:4,title:"أربعة مفاهيم",note:"معالجة شبكة علاقات متعددة ورفع تعقيد المقارنة."}
];
export default function VennBuilder(){
 const {projectId,project,saveTool,nextHref}=useTeacherProject(); const [saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 const [step,setStep]=useState(1),[subject,setSubject]=useState(""),[grade,setGrade]=useState(""),[lesson,setLesson]=useState(""),[goal,setGoal]=useState(""),[count,setCount]=useState(2),[concepts,setConcepts]=useState(["","","",""]),[prompt,setPrompt]=useState(""),[evidence,setEvidence]=useState("");

 useEffect(()=>{if(project){setSubject(project.subject||"");setGrade(project.grade||"");setLesson(project.lesson||project.title||"");setGoal(project.learning_goal||"");const old=project.project_data?.concepts;if(old){setCount(old.count||2);if(old.concepts)setConcepts(old.concepts);setPrompt(old.prompt||\"\");setEvidence(old.evidence||\"\")}}},[project]); const valid=useMemo(()=>subject.trim()&&lesson.trim()&&goal.trim(),[subject,lesson,goal]); const active=concepts.slice(0,count);
 function setConcept(i:number,v:string){setConcepts(x=>x.map((c,n)=>n===i?v:c))}
 return <main className="vennBuilder">
  <header className="tierTop"><Link href="/teacher/lab">مختبر التمايز <ArrowLeft size={14}/></Link><div><GitCompareArrows/><b>أشكال فن</b></div><span>أداة تمايز المحتوى والعملية</span></header>
  <section className="tierIntro"><span>أداة 03 • المقارنة والتعقيد</span><h1>غيّر تعقيد المعالجة.<br/>ولا تغيّر الهدف بلا سبب.</h1><p>ابدأ بالمفاهيم التي تريد من الطلاب معالجتها، ثم اختر بنية المقارنة المناسبة. زيادة عدد المفاهيم ترفع شبكة العلاقات التي يحتاج الطالب إلى فحصها.</p></section>
  <nav className="builderSteps">{["الهدف","درجة التعقيد","بناء المهمة","المخرج"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
  {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>حدد الفهم الذي تريد أن تكشفه المقارنة</h2><p>شكل فن وسيلة لمعالجة المفاهيم والعلاقات، وليس نشاط رسم بحد ذاته.</p></div></div><div className="formGrid"><label>المادة<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="مثال: الأحياء"/></label><label>الصف<input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="مثال: أول ثانوي"/></label><label className="wide">عنوان الدرس<input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="عنوان الدرس"/></label><label className="wide">ناتج التعلم<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="ما الفهم الذي ينبغي أن يظهره الطالب من المقارنة؟"/></label></div><button className="builderNext" disabled={!valid} onClick={()=>setStep(2)}>اختيار درجة التعقيد <ChevronLeft/></button></section>}
  {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>كم مفهومًا سيعالج الطالب؟</h2><p>لا تجعل العدد مستوى ثابتًا للطالب؛ اختره وفق الجاهزية وطبيعة الهدف.</p></div></div><div className="vennModes">{modes.map(m=><button key={m.n} className={count===m.n?"active":""} onClick={()=>setCount(m.n)}><VennMini count={m.n}/><b>{m.title}</b><span>{m.note}</span></button>)}</div><div className="complexityScale"><span>أقل تعقيدًا</span><i/><strong>{count} / 4</strong><i/><span>أكثر تعقيدًا</span></div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" onClick={()=>setStep(3)}>بناء المهمة <ChevronLeft/></button></div></section>}
  {step===3&&<section className="builderCard wideCard"><div className="builderHead"><span>03</span><div><h2>سمِّ المفاهيم واكتب مهمة التفكير</h2><p>اجعل الطالب يبحث عن العلاقات ذات المعنى، لا مجرد قائمة صفات سطحية.</p></div></div><div className="vennWorkspace"><div className={"vennCanvas count"+count}>{active.map((c,i)=><div className={"vennCircle c"+i} key={i}><span>{c||("المفهوم "+(i+1))}</span></div>)}</div><div className="vennFields">{active.map((c,i)=><label key={i}>{"المفهوم "+(i+1)}<input value={c} onChange={e=>setConcept(i,e.target.value)} placeholder={"اكتب المفهوم "+(i+1)}/></label>)}<label className="full">مهمة الطالب<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="قارن ثم فسّر العلاقة الأهم التي توصلت إليها وادعمها بدليل."/></label><label className="full">دليل التعلم المطلوب<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="كيف سيُظهر الطالب فهمه بعد إكمال الشكل؟"/></label></div></div><div className="builderActions"><button onClick={()=>setStep(2)}>السابق</button><button className="builderNext" onClick={()=>setStep(4)}>معاينة المخرج <ChevronLeft/></button></div></section>}
  {step===4&&<section className="builderCard reviewCard"><div className="builderHead"><span>04</span><div><h2>نشاط فن جاهز للمراجعة</h2><p>{subject} • {grade} • {lesson}</p></div></div><div className="goalReview"><span>ناتج التعلم</span><b>{goal}</b></div><div className="vennOutput"><div className={"vennCanvas count"+count}>{active.map((c,i)=><div className={"vennCircle c"+i} key={i}><span>{c||("المفهوم "+(i+1))}</span></div>)}</div><article><span>مهمة الطالب</span><b>{prompt||"لم تُكتب المهمة بعد."}</b><span>دليل التعلم</span><p>{evidence||"لم يُحدد دليل التعلم بعد."}</p></article></div><div className="vennQuality"><Check/><span>المفاهيم مرتبطة بالهدف.</span><Check/><span>زيادة الدوائر تعني معالجة علاقات أكثر، لا عملاً أكثر فقط.</span><Check/><span>المهمة تطلب تفسيرًا أو استدلالًا يتجاوز ملء الشكل.</span></div><div className="builderActions"><button onClick={()=>setStep(3)}>تعديل النشاط</button><button className="builderNext" disabled={saving} onClick={async()=>{setSaving(true);try{await saveTool("concepts",{count,concepts,prompt,evidence,updated_at:new Date().toISOString()});setSaved(true)}finally{setSaving(false)}}}><Sparkles/> {saved?"تم الحفظ":saving?"جارٍ الحفظ…":"حفظ في المشروع"}</button>${saved&&nextHref("concepts")&&<Link className="builderNext" href={nextHref("concepts")!}>التالي <ChevronLeft/></Link>}</div></section>}
 {projectId&&<div className="projectContextBar"><span>المشروع: <b>{project?.title||"الدرس المتمايز"}</b></span><Link href="/teacher/library">مكتبتي</Link></div>}</main>
}
function VennMini({count}:{count:number}){return <div className={"vennMini n"+count}>{Array.from({length:count}).map((_,i)=><i key={i}/>)}</div>}
