"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {ArrowLeft,Check,ChevronLeft,Compass,Lightbulb,MessageCircleQuestion,Sparkles,Target} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
const focuses=[
 ["دليل التعلم","هل قراراتي مبنية على دليل كافٍ من تعلم الطلاب؟"],
 ["الجاهزية والتدرج","هل أغيّر الدعم والتحدي وفق جاهزية متغيرة؟"],
 ["عمق التفكير","هل المهام تغيّر التفكير الفعلي لا الأفعال الظاهرية فقط؟"],
 ["اختيار المتعلم","هل الخيارات حقيقية ومقصودة وتعود إلى هدف مشترك؟"],
 ["التشغيل الصفي","هل التنظيم يتيح لي التدخل في المكان والوقت المناسبين؟"]
];
export default function Coaching(){
 const router=useRouter(),[projects,setProjects]=useState<any[]>([]),[refs,setRefs]=useState<any[]>([]),[step,setStep]=useState(1),[projectId,setProjectId]=useState(""),[focus,setFocus]=useState(""),[reflection,setReflection]=useState(""),[goal,setGoal]=useState(""),[action,setAction]=useState(""),[success,setSuccess]=useState(""),[review,setReview]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const [{data:p},{data:r}]=await Promise.all([s.from("teacher_differentiation_projects").select("id,title,status,project_data,updated_at").order("updated_at",{ascending:false}),s.from("teacher_project_reflections").select("*").order("created_at",{ascending:false})]);setProjects(p||[]);setRefs(r||[])})()},[]);
 const selected=projects.find(p=>p.id===projectId), evidence=useMemo(()=>{if(!projectId)return "";const r=refs.find(x=>x.project_id===projectId);if(!r)return "لا يوجد تأمل موثق لهذا المشروع بعد.";return "الدليل: "+r.evidence+"\nالقرار السابق: "+r.next_decision},[projectId,refs]);
 async function save(){setSaving(true);try{const s=getSupabaseBrowserClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("يلزم تسجيل الدخول");const {error}=await s.from("teacher_coaching_cycles").insert({teacher_id:user.id,project_id:projectId||null,focus,evidence,reflection,development_goal:goal,action_step:action,success_evidence:success,review_date:review||null});if(error)throw error;router.push("/teacher/growth")}finally{setSaving(false)}}
 return <main className="coachingPage"><header className="tierTop"><Link href="/teacher/growth">مساري المهني <ArrowLeft size={14}/></Link><div><Compass/><b>جلسة كوتشينق</b></div><span>دليل • سؤال • هدف • إجراء</span></header>
 <section className="coachHero"><span>COACHING CONVERSATION</span><h1>لا تبدأ بالحكم.<br/>ابدأ بالدليل والسؤال.</h1><p>جلسة قصيرة تحول خبرة صفية محددة إلى هدف تطوير قابل للتطبيق، ثم تحدد الدليل الذي سيخبرك أن التغيير أحدث أثرًا.</p></section>
 <nav className="builderSteps">{["اختر الدليل","سؤال التأمل","هدف التطوير","اتفاق الإجراء"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
 {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>اختر ممارسة حقيقية للنقاش</h2><p>يمكن أن تبدأ من درس مطبق، أو من نمط لاحظته في ممارستك.</p></div></div><label className="standalone">المشروع / الدرس<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">بدون مشروع محدد</option>{projects.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label>{projectId&&<div className="coachEvidence"><b>{selected?.title}</b><pre>{evidence}</pre></div>}<button className="builderNext" onClick={()=>setStep(2)}>اختيار محور التأمل <ChevronLeft/></button></section>}
 {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>اختر السؤال الذي يستحق التوقف عنده</h2><p>المنصة لا تقرر عنك؛ هي تساعدك على فحص ممارسة محددة.</p></div></div><div className="coachFocuses">{focuses.map(([f,q])=><button className={focus===f?"active":""} onClick={()=>setFocus(f)} key={f}><MessageCircleQuestion/><b>{f}</b><span>{q}</span></button>)}</div><label className="reflectField">تأملي حول هذا السؤال<textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="ماذا يخبرني الدليل؟ ما الفرضية التي أحتاج اختبارها؟"/></label><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" disabled={!focus||!reflection.trim()} onClick={()=>setStep(3)}>صياغة الهدف <ChevronLeft/></button></div></section>}
 {step===3&&<section className="builderCard"><div className="builderHead"><span>03</span><div><h2>حوّل التأمل إلى هدف تطوير قصير</h2><p>اجعله قريبًا من الصف ويمكن اختباره خلال تطبيق أو تطبيقين، لا شعارًا عامًا.</p></div></div><label className="reflectField">هدف التطوير<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="مثال: تحسين دقة تشكيل المجموعات باستخدام دليل جاهزية قصير قبل المهمة."/></label><div className="goalFormula"><Target/><span><b>صيغة مفيدة:</b> سأحسن [ممارسة محددة] لكي [أثر تعلم متوقع]، وسأتحقق من ذلك عبر [دليل].</span></div><div className="builderActions"><button onClick={()=>setStep(2)}>السابق</button><button className="builderNext" disabled={!goal.trim()} onClick={()=>setStep(4)}>اتفاق الإجراء <ChevronLeft/></button></div></section>}
 {step===4&&<section className="builderCard reviewCard"><div className="builderHead"><span>04</span><div><h2>اتفاق تطوير مهني صغير وقابل للقياس</h2><p>إجراء واحد واضح أفضل من قائمة طويلة لا تصل إلى الحصة.</p></div></div><div className="reflectGrid"><label>الإجراء الذي سأجربه<textarea value={action} onChange={e=>setAction(e.target.value)} placeholder="ما التغيير الذي ستطبقه في الدرس القادم؟"/></label><label>دليل النجاح<textarea value={success} onChange={e=>setSuccess(e.target.value)} placeholder="ما الذي ستراه أو تجمعه لتعرف أن الإجراء أحدث فرقًا؟"/></label><label className="wide">موعد المراجعة<input type="date" value={review} onChange={e=>setReview(e.target.value)}/></label></div><div className="coachAgreement"><Lightbulb/><div><small>محور الكوتشينق</small><b>{focus}</b><small>هدف التطوير</small><p>{goal}</p></div></div><button className="saveReflection" disabled={saving||!action.trim()||!success.trim()} onClick={save}><Sparkles/>{saving?"جارٍ الحفظ…":"اعتماد دورة التطوير"}</button></section>}
 </main>
}