"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BrainCircuit,Check,ChevronLeft,Plus,Sparkles} from "lucide-react";

type BloomRow={level:string,meaning:string,process:string,product:string};
const initial:BloomRow[]=[
 {level:"التذكر",meaning:"استدعاء المعرفة والمعلومات ذات الصلة.",process:"",product:""},
 {level:"الفهم",meaning:"بناء معنى وشرح الفكرة أو تمثيلها.",process:"",product:""},
 {level:"التطبيق",meaning:"استخدام التعلم في موقف أو مهمة.",process:"",product:""},
 {level:"التحليل",meaning:"تفكيك المعلومات وفحص العلاقات والأنماط.",process:"",product:""},
 {level:"التقويم",meaning:"إصدار حكم مبرر وفق محكات أو أدلة.",process:"",product:""},
 {level:"الإبداع",meaning:"بناء أو إنتاج شيء جديد يحقق غرضًا واضحًا.",process:"",product:""}
];
export default function BloomBuilder(){
 const [step,setStep]=useState(1),[subject,setSubject]=useState(""),[grade,setGrade]=useState(""),[lesson,setLesson]=useState(""),[goal,setGoal]=useState(""),[content,setContent]=useState(""),[rows,setRows]=useState(initial);
 const valid=useMemo(()=>subject.trim()&&lesson.trim()&&goal.trim(),[subject,lesson,goal]);
 function update(i:number,key:"process"|"product",v:string){setRows(x=>x.map((r,n)=>n===i?{...r,[key]:v}:r))}
 return <main className="bloomBuilder">
  <header className="tierTop"><Link href="/teacher/lab">مختبر التمايز <ArrowLeft size={14}/></Link><div><BrainCircuit/><b>بلوم المعدل</b></div><span>أداة بناء تجربة التعلم</span></header>
  <section className="tierIntro bloomIntro"><span>أداة 02 • عمق التفكير</span><h1>لا تغيّر الفعل فقط.<br/>غيّر التفكير الذي تتطلبه المهمة.</h1><p>ابنِ خبرات تعلم تختلف في مستوى العملية المعرفية، مع إبقاء المحتوى وناتج التعلم واضحين. الهدف ليس ملء المستويات الستة آليًا، بل اختيار العمق الذي يخدم التعلم.</p></section>
  <nav className="builderSteps">{["الهدف والمحتوى","عمق التفكير","العملية والمنتج","مراجعة"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{step>i+1?<Check/>:i+1}</b><span>{x}</span></div>)}</nav>
  {step===1&&<section className="builderCard"><div className="builderHead"><span>01</span><div><h2>ابدأ بما سيتعلمه الطالب</h2><p>المحتوى هو المعرفة والمفاهيم والمهارات التي ينبغي أن يصل إليها المتعلم.</p></div></div><div className="formGrid"><label>المادة<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="مثال: العلوم"/></label><label>الصف<input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="مثال: أول ثانوي"/></label><label className="wide">عنوان الدرس<input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="عنوان الدرس أو المفهوم"/></label><label className="wide">ناتج التعلم<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="ما الفهم أو الأداء الذي تريد أن يصل إليه الطالب؟"/></label><label className="wide">المحتوى الرئيس<textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="المفاهيم، الحقائق، المبادئ أو المهارات التي سيعمل عليها الطلاب."/></label></div><button className="builderNext" disabled={!valid} onClick={()=>setStep(2)}>التالي: خريطة التفكير <ChevronLeft/></button></section>}
  {step===2&&<section className="builderCard"><div className="builderHead"><span>02</span><div><h2>افحص ما الذي يتطلبه التفكير فعلًا</h2><p>قد تستخدم المهمة فعلًا يبدو عالي المستوى، بينما لا تتطلب من الطالب إلا استدعاءً أو فهمًا سطحيًا. ركز على العملية العقلية الفعلية.</p></div></div><div className="bloomLadder">{rows.map((r,i)=><article key={r.level} className={"bloomLevel b"+(i+1)}><b>{i+1}</b><div><h3>{r.level}</h3><p>{r.meaning}</p></div><button onClick={()=>{setStep(3);document.documentElement.style.setProperty("--focusBloom",String(i))}}>استخدم هذا العمق</button></article>)}</div><div className="builderActions"><button onClick={()=>setStep(1)}>السابق</button><button className="builderNext" onClick={()=>setStep(3)}>صمّم التجارب <ChevronLeft/></button></div></section>}
  {step===3&&<section className="builderCard wideCard"><div className="builderHead"><span>03</span><div><h2>اربط العملية بالمنتج</h2><p>العملية: ماذا سيفعل الطالب ليتعلم؟ المنتج: كيف سيظهر تعلمه؟ اكتب تجربة حقيقية، لا فعلًا منفردًا.</p></div></div><div className="bloomMatrix"><div className="matrixHead"><span>المستوى</span><span>العملية / تجربة التعلم</span><span>المنتج / دليل التعلم</span></div>{rows.map((r,i)=><div className="matrixRow" key={r.level}><div><b>{r.level}</b><small>{r.meaning}</small></div><textarea value={r.process} onChange={e=>update(i,"process",e.target.value)} placeholder="ماذا سيفعل الطالب ليفكر ويتعلم؟"/><textarea value={r.product} onChange={e=>update(i,"product",e.target.value)} placeholder="كيف سيُظهر هذا التعلم؟"/></div>)}</div><div className="bloomCaution"><Sparkles/><div><b>فحص الجودة</b><span>ليس مطلوبًا استخدام المستويات الستة في كل درس. اختر ما يخدم الهدف والجاهزية، وتأكد أن اختلاف المهمة يعكس اختلافًا حقيقيًا في التفكير.</span></div></div><div className="builderActions"><button onClick={()=>setStep(2)}>السابق</button><button className="builderNext" onClick={()=>setStep(4)}>مراجعة التجربة <ChevronLeft/></button></div></section>}
  {step===4&&<section className="builderCard reviewCard"><div className="builderHead"><span>04</span><div><h2>خريطة عمق التفكير للدرس</h2><p>{subject} • {grade} • {lesson}</p></div></div><div className="goalReview"><span>ناتج التعلم</span><b>{goal}</b><small>{content}</small></div><div className="bloomReview">{rows.filter(r=>r.process||r.product).map(r=><article key={r.level}><b>{r.level}</b><div><small>العملية</small><span>{r.process||"—"}</span></div><div><small>المنتج</small><span>{r.product||"—"}</span></div></article>)}</div>{!rows.some(r=>r.process||r.product)&&<div className="emptyBloom">لم تُضف تجارب بعد. ارجع إلى المصفوفة وأضف المستويات التي تخدم هدف الدرس.</div>}<div className="builderActions"><button onClick={()=>setStep(3)}>تعديل الخريطة</button><button className="builderNext"><Sparkles/> حفظ في مكتبتي</button></div></section>}
 </main>
}